service:
  name: transform-for-alexa-audios
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 128
  timeout: 16
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::transform-for-alexa-audios/*"
package:
  exclude:
    - '*.js'
    - '*.yml'
  include:
    - handler.js
  excludeDevDependencies: false
functions:
  transform:
    handler: handler.transform
    events:
      - s3:
          bucket: transform-for-alexa-audios
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .mp3
      - http:
          path: audios/transform
          method: post
