service:
  name: transform-for-alexa-audios
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 128
  timeout: 16
  environment: ${file(./env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.bucketName}/*"
package:
  exclude:
    - '*.js'
    - '*.yml'
  include:
    - handler.js
    - ffmpeg
  excludeDevDependencies: false
functions:
  transform:
    handler: handler.transform
    events:
      - s3:
          bucket: ${self:provider.environment.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
            - suffix: .mp3
